
import { Product, ProductCategory } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'prod_001',
    name: 'Fresh Farm Milk',
    category: ProductCategory.MILK,
    description: 'Pure, pasteurized whole milk, rich in calcium and vitamins. Perfect for your daily needs.',
    imageUrl: 'https://picsum.photos/seed/milk/400/400',
    price_unit: 1.50,
    price_carton: 15.00,
    carton_size: 12,
    stock: 250,
  },
  {
    id: 'prod_002',
    name: 'Natural Greek Yogurt',
    category: ProductCategory.YOGURT,
    description: 'Thick and creamy Greek yogurt, high in protein. A healthy and delicious snack.',
    imageUrl: 'https://picsum.photos/seed/yogurt1/400/400',
    price_unit: 2.20,
    price_carton: 22.50,
    carton_size: 12,
    stock: 180,
  },
  {
    id: 'prod_003',
    name: 'Strawberry Flavored Yogurt',
    category: ProductCategory.YOGURT,
    description: 'Deliciously sweet yogurt with real strawberry pieces. A treat for all ages.',
    imageUrl: 'https://picsum.photos/seed/yogurt2/400/400',
    price_unit: 1.80,
    price_carton: 19.00,
    carton_size: 12,
    stock: 200,
  },
  {
    id: 'prod_004',
    name: 'Low-Fat Milk',
    category: ProductCategory.MILK,
    description: 'A lighter option with the same great taste. 2% fat milk for a healthy lifestyle.',
    imageUrl: 'https://picsum.photos/seed/lowfatmilk/400/400',
    price_unit: 1.40,
    price_carton: 14.00,
    carton_size: 12,
    stock: 150,
  },
  {
    id: 'prod_005',
    name: 'Aged Cheddar Cheese',
    category: ProductCategory.CHEESE,
    description: 'Sharp and savory aged cheddar block. Perfect for sandwiches, platters, or cooking.',
    imageUrl: 'https://picsum.photos/seed/cheese/400/400',
    price_unit: 7.50,
    price_carton: 80.00,
    carton_size: 12,
    stock: 90,
  },
  {
    id: 'prod_006',
    name: 'Salted Butter Sticks',
    category: ProductCategory.BUTTER,
    description: 'Creamy, rich salted butter made from fresh cream. Ideal for baking and spreading.',
    imageUrl: 'https://picsum.photos/seed/butter/400/400',
    price_unit: 4.00,
    price_carton: 45.00,
    carton_size: 12,
    stock: 120,
  },
    {
    id: 'prod_007',
    name: 'Vanilla Bean Yogurt',
    category: ProductCategory.YOGURT,
    description: 'Smooth yogurt infused with real vanilla bean flecks for a rich, aromatic flavor.',
    imageUrl: 'https://picsum.photos/seed/yogurt3/400/400',
    price_unit: 2.30,
    price_carton: 24.00,
    carton_size: 12,
    stock: 160,
  },
    {
    id: 'prod_008',
    name: 'Chocolate Milk',
    category: ProductCategory.MILK,
    description: 'A classic favorite. Rich chocolate milk that\'s both a treat and a source of calcium.',
    imageUrl: 'https://picsum.photos/seed/chocomilk/400/400',
    price_unit: 1.90,
    price_carton: 20.00,
    carton_size: 12,
    stock: 130,
  },
];
